name: xhospitals
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7
  fluttertoast: ^8.0.7
  #flutter_screenutil: ^5.0.0+2
  google_fonts: 2.2.0
  flutter_datetime_picker: ^1.5.1
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  dots_indicator: ^2.1.0
  month_picker_dialog: ^0.4.0
  flutter_launcher_icons: ^0.9.0
  avatars: ^3.0.0
  agora_rtc_engine: ^5.1.0
  permission_handler: ^8.0.1
  sizer: ^2.0.15
  firebase_messaging: ^11.2.13
  firebase_core: ^1.14.1
  flutter_local_notifications: ^9.4.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: sfprodisplay
      fonts:
        - asset: assets/sfpdt.ttf
          weight: 100
        - asset: assets/sfpdel.ttf
          weight: 200
        - asset: assets/sfpdl.ttf
          weight: 300
        - asset: assets/sfpdr.ttf
          weight: 400
        - asset: assets/sfpdm.ttf
          weight: 500
        - asset: assets/sfpds.ttf
          weight: 600
        - asset: assets/sfpdbo.ttf
          weight: 700
        - asset: assets/sfpdbl.ttf
          weight: 800
        - asset: assets/sfpdh.ttf
          weight: 900